name: Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/UnitTests.yml'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'
  pull_request:
    paths:
      - '.github/workflows/UnitTests.yml'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'

jobs:
  test:
    name: Julia ${{ matrix.julia_version }} - ${{ matrix.os }}
    permissions:
      actions: write
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia_version:
          - lts
          - '1'
          - pre
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia_version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          annotate: false
          coverage: false
